# Generated by Django 4.2.2 on 2023-06-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Курс',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Аноним', max_length=200, verbose_name='Пользователь')),
                ('surname', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Преподаватели',
                'ordering': ('surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Аноним', max_length=200, verbose_name='Пользователь')),
                ('surname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_students.course')),
            ],
            options={
                'verbose_name': 'Студенты',
                'ordering': ('surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Аноним', max_length=200, verbose_name='Пользователь')),
                ('date', models.DateTimeField()),
                ('classroom', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_students.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_students.teacher')),
            ],
            options={
                'verbose_name': 'Занятия',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_students.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_students.student')),
            ],
            options={
                'verbose_name': 'Оценка',
            },
        ),
    ]
